export const PFC_DETAILED_TO_CATEGORY: Record<string, string> = {
  // Income
  INCOME_DIVIDENDS: "Investment Income",
  INCOME_INTEREST_EARNED: "Investment Income",
  INCOME_WAGES: "Salary",
  INCOME_RETIREMENT_PENSION: "Other Income",
  INCOME_TAX_REFUND: "Other Income",
  INCOME_UNEMPLOYMENT: "Other Income",
  INCOME_OTHER_INCOME: "Other Income",

  // Housing
  RENT_AND_UTILITIES_RENT: "Rent/Mortgage",
  LOAN_PAYMENTS_MORTGAGE_PAYMENT: "Rent/Mortgage",
  HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE: "Maintenance",
  HOME_IMPROVEMENT_HARDWARE: "Maintenance",
  HOME_IMPROVEMENT_FURNITURE: "Home Goods",

  // Food & Dining
  FOOD_AND_DRINK_RESTAURANTS: "Restaurants",
  FOOD_AND_DRINK_FAST_FOOD: "Restaurants",
  FOOD_AND_DRINK_GROCERIES: "Groceries",
  FOOD_AND_DRINK_COFFEE: "Coffee Shops",
  FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR: "Restaurants",
  FOOD_AND_DRINK_VENDING_MACHINES: "Restaurants",
  FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK: "Restaurants",

  // Transportation
  TRANSPORTATION_GAS: "Gas",
  TRANSPORTATION_PUBLIC_TRANSIT: "Public Transit",
  TRANSPORTATION_PARKING: "Parking",
  TRANSPORTATION_TOLLS: "Parking",
  TRANSPORTATION_RIDE_SHARE: "Public Transit",
  TRANSPORTATION_TAXIS: "Public Transit",
  TRANSPORTATION_OTHER_TRANSPORTATION: "Public Transit",
  LOAN_PAYMENTS_CAR_PAYMENT: "Car Payment",

  // Utilities
  RENT_AND_UTILITIES_ELECTRIC: "Electric",
  RENT_AND_UTILITIES_WATER: "Water",
  RENT_AND_UTILITIES_INTERNET_AND_CABLE: "Internet",
  RENT_AND_UTILITIES_TELEPHONE: "Phone",
  RENT_AND_UTILITIES_GAS: "Electric",
  RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT: "Water",
  RENT_AND_UTILITIES_OTHER_UTILITIES: "Electric",

  // Shopping
  GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES: "Clothing",
  GENERAL_MERCHANDISE_ELECTRONICS: "Electronics",
  GENERAL_MERCHANDISE_DEPARTMENT_STORES: "Home Goods",
  GENERAL_MERCHANDISE_DISCOUNT_STORES: "Home Goods",
  GENERAL_MERCHANDISE_SUPERSTORES: "Home Goods",
  GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES: "Gifts",
  GENERAL_MERCHANDISE_ONLINE_MARKETPLACES: "Home Goods",
  GENERAL_MERCHANDISE_SPORTING_GOODS: "Home Goods",
  GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE: "Home Goods",

  // Health
  MEDICAL_HEALTH_INSURANCE: "Health Insurance",
  MEDICAL_DENTIST_AND_OPTOMETRIST: "Medical",
  MEDICAL_DOCTOR: "Medical",
  MEDICAL_HOSPITAL: "Medical",
  MEDICAL_PHARMACY: "Pharmacy",
  MEDICAL_VETERINARY_SERVICES: "Medical",
  MEDICAL_OTHER_MEDICAL: "Medical",
  PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS: "Fitness",
  PERSONAL_CARE_HAIR_AND_BEAUTY: "Entertainment",
  PERSONAL_CARE_OTHER_PERSONAL_CARE: "Entertainment",

  // Personal
  ENTERTAINMENT_MUSIC_AND_AUDIO: "Entertainment",
  ENTERTAINMENT_MOVIES_AND_DVDS: "Entertainment",
  ENTERTAINMENT_GAMES: "Entertainment",
  ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS: "Entertainment",
  ENTERTAINMENT_CASINOS_AND_GAMBLING: "Entertainment",
  ENTERTAINMENT_TV_AND_MOVIES: "Subscriptions",
  ENTERTAINMENT_OTHER_ENTERTAINMENT: "Entertainment",
  GENERAL_SERVICES_EDUCATION: "Education",
  LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT: "Education",
  TRAVEL_FLIGHTS: "Travel",
  TRAVEL_LODGING: "Travel",
  TRAVEL_RENTAL_CARS: "Travel",
  TRAVEL_OTHER_TRAVEL: "Travel",
};
